### ISSUE TITLE
Allow miner mobs to drop the blocks they mine

### ISSUE THREAD

**Issue by DoomRater** [Corosauce/HostileWorlds_Invasions#1]
One thing I would really like is if the miner zombie could either collect drops on the ground and drop them on death, or at least cause anything mined to drop on the ground if they can't collect AND drop on death.  That keeps them from permanently destroying expensive to replace machine blocks.

**Comment by laserlemons** [comment]
The blocks aren't actually broken, it's more like they are temporarily disabled. They reappear in when the invasion ends.

**Comment by Corosauce** [comment]
Yeah when it was originally posted the repairing block feature didn't exist, but side from tile entities they wont touch, there are still some regular blocks I cant convert to repairing blocks (like doors). At this point the mod has really good support for breaking a block the way a player does so it drops an itemized version of it on the ground, so I might as well close this issue, kinda forgot about it.
