### ISSUE TITLE
Bug: Dimension Change Blocker not always working during invasions. (Especially on servers)

### ISSUE THREAD

**Issue by SirAron111** [Corosauce/HostileWorlds_Invasions#12]
Ok I noticed that certain ways to Change Dimensions During an invasion aren’t blocked for example The Spectral Key from Random Things teleporting the player to the pocket dimension or the Dimension Changer from aroma Mining Dimension seem to always work.  I know that teleporting items can be blocked as for example the Grave key from tombstones can’t port you to your grave during an invasion.

Also if the player is in another Dimension during an invasion he can just stay there and ignore the invasion. There should be a config option to force teleport the Player out of any other Dimension than the Over world once his Invasion starts. Maybe with a little timer message popping up! Like: “You will be teleported back to your spawn point in 10 seconds as an invasion is about to happen” (If text is configurable I would in my pack say something like “Akashic: I will have to teleport you back to your save point in 10 seconds. A Rift is about to open! Other Dimensions are too unstable during this time.”)

This would help prevent players just staying in the nether when they know an invasion is about to happen or teleporting to the save little pocket dimension. Especially on Servers as the Over world mostly doesn’t unload when a player is in another dimension.

GZ
SirAron

**Comment by CalaMariGold** [comment]
> There should be a config option to force teleport the Player out of any other Dimension than the Over world once his Invasion starts. Maybe with a little timer message popping up! Like: “You will be teleported back to your spawn point in 10 seconds as an invasion is about to happen”

Yes! My modpack very much needs this!

**Comment by Corosauce** [comment]
Yeah some dimensions are tricky I guess, so that solution should do well, it is done.

You can customize how long a player has before being force teleported, and the messages themselves, not perfect, but a good start.

![2019-12-28_19 27 51](https://user-images.githubusercontent.com/1238621/71551322-094ac000-29b3-11ea-82a2-d02f5fb23990.png)

**Comment by SirAron111** [comment]
Sounds good will try that as soon as I get to it. Hope it brings players to the set spawn point not the world spawn which is important for servers XD will let you know as soon as I get to it.
