### ISSUE TITLE
The sacrifice Block doesn’t take the item set in the new configs for the night skip and still just takes blood (does a tiny bit of player dmg)

### ISSUE THREAD

**Issue by SirAron111** [Corosauce/HostileWorlds_Invasions#15]
The sacrifice Block doesn’t take the item set in the new configs for the night skip and still just takes blood (does a tiny bit of player dmg)

**Comment by Corosauce** [comment]
forgot to flag all those configs as unused, feature isnt done yet.

**Comment by SirAron111** [comment]
A ok can’t wait for them to be completed I really liked the idea of making it more and more difficulty to skip consecutively (the item I was going to use was one you can only get as loot from mobs if you kill them as player so losing them would be a choice to make especially in hardcore)
