### ISSUE TITLE
Suggestions: about customizable invasions

### ISSUE THREAD

**Issue by SirAron111** [Corosauce/HostileWorlds_Invasions#2]
Suggestions about customizable invasions
In the page you say:
“Highly configurable invasion system for building your own invasions to have literally anything invade you with various buffs, even infernal mobs buffs, but documentation for all of this is still very much a work in progress.”

Well since I couldn’t find a way to customize them I wanted to request these things sry if they already exist.

1.	Option to make reappearing blocks reappear faster.
1.	Option to make Enderman or creepers that spawn during the invasion steal/explode blocks (but have them replaced with reappearing blocks) even if game rules say no grifing for them.
2.	Option to add custom invasions (like making lists of entities that can invade the player this way Modpack makers could add to the normal invasions some custom ones like embers:ancientgolem, iceandfire:dragon etc for really hard invasions (or funny bunny invasions))
3.	Option to decide what the altar needs in order to skip an invasion (setting an item in the configs)

**Comment by Corosauce** [comment]
I've pushed new builds to my site and curse so be sure to get those before reading more.

I've been pushing towards a proper release, so heres the wiki I've got for customizing I just did a first draft on yesterday, probably far from perfect but its a start: [http://coros.us/wiki/index.php?title=Hostile_Worlds_-_Invasions_-_Customizing](http://coros.us/wiki/index.php?title=Hostile_Worlds_-_Invasions_-_Customizing)

1. I assume your mean repairing blocks. Made their repair rate config more obvious now. see ticksToRepairBlock in config/coroutil/DynamidDifficulty.cfg

2. Im making explosions by default create repairing blocks during invasions now. BUT it looks like if the mobGriefing gamerule is on. I can't tell what a creeper might have damaged, so I dont think i can do this if that rule is on without some crazy hacks that would be way too much effort to try.

3. Exactly what I had in mind, see the wiki link above.

4. Interesting idea, I like it. I'll have to think about it, as currently just sacrificing some health is a bit easy.

**Comment by SirAron111** [comment]
1. Thx the wiki was really helpful and the new config help allot I managed to make invasions of multiple Moded mobs like goblin hordes or grimoir of gaia invasions, if I could make mobs fly I would even make a squid invasion thought they would all die out of water XD
But for some reason I can’t get them to work I set the time for invasions to every day for testing purposes but it only spawns the standard mobs not the ones I added at the bottom. Here is the file
https://pastebin.com/h27Bcd9z

2. Can’t wait for the config to set an item for the sacrifice

3.also the explosion option for creepers works just fine

4. I just need to figure out the scaling factors a bit better to not make them super op with the scaling difficulty mod ramping mob and player health as well as dmg up by a lot.

**Comment by SirAron111** [comment]
A I found the problem I had with the config I had a (  , ) where it shouldn’t be XD now it all works just fine. But there should be an option to make mobs spawned from the invasions disappear at day time since not all mobs burn in sunlight and having for example a horde of goblins spawn that stay around you like forever is harder than intended.

**Comment by Corosauce** [comment]
Glad to see you testing the system :D I've been rapidly finding and fixing bugs as I am testing it on a friends server at the moment.

Yeah for killing off invaders, such options have crossed my mind and I need to add something for it soon, especially with the invasions I added like crazy animals, they currently just hang around after the invasion if they weren't killed.

I'll either:
1. Use a sort of "wander away" AI that will make them stop attacking the player and just run away until they get far enough then allow despawn or just kill them
2. Just strait up kill them right away or some forced damage over time as if theyre allergic to sunlight anywhere or something.

Flying support needs a lot of work and might never be fully supported which is also mentioned in the wiki.

At some point I'm going to play around with modded mobs that fly and see what the best solution will be, worst case I try something like force moving entities around as if they fly just to get them close enough to you so that the modded mobs AI can then take over and do whatever it does to be hostile towards you flying around etc.

I also added a json validator link to the wiki which might help you catch syntax problems quicker.

**Comment by SirAron111** [comment]
Well the way I  set it up at the moment it works super well with the story of my modpack and with the waves (every 4 days is good since I also have scaling difficulty and other things) if you want to test it  for mod compatibility or other things I can only recommend you try abusing my modpack for it XD just download it and mess around with it and see if you can find bugs I have over 200 mods in it and a lot of moded mobs and a lot of them added to the invasions I bet it would help you find bugs (I will report any I find to my community loves the invasions so far).

https://minecraft.curseforge.com/projects/dimension-zero here is a link to the curse page.

**Comment by Corosauce** [comment]
Ah sweet! I just might, thanks!

Also I didn't have it in me to try adding a flee after invasion AI routine yet, so today I added a way to do damage over time to invaders once the sun rises, on latest build open up InvasionConfig.cfg and set damagePerSecondToInvadersAtSunrise to something like 3, worked well in testing.

**Comment by SirAron111** [comment]
I will thanks (thought I will set it to something like 100 or o since mobs once gain hp over time due to scaling health mod this also includes the invasion mobs (which is good) )
I haven’t tested it ye but do they still drop items after they die from this dmg? Since this would give immense loot spam and unless they were damaged by a player shouldn’t drop loot.

**Comment by SirAron111** [comment]
Yep tested it works great only problems I could name would be
1.	Monsters that get for example turned to stone or similar moded monsters like ice and fire trolls/ primitive mobs trollager) will not take dmg in that form and instead just keep flashing the effect of being on fire one and off.
2.	Witches keep healing themselves with potions for all eternity if dmg isn’t set high enough to counter this (no problem for me I set dot dmg to 50)
3.	Since it’s not a mob vanishing but rather a mobs dying from dmg they do drop loot so on day break a lot of items lay on the ground (not much of a problem for me just wanted to say this since some people don’t like this)

But all in all great feature so far makes  surviving the night more rewarding and not so oppressing when hp go so high that zombies burn to slow or modded monsters that don’t despawn stay around.

**Comment by SirAron111** [comment]
An option to disable the recipe for the sacrifice block would be nice since no matter how I try to remove the recipe (and then force to use my custom one) the recipe with the gold and rotten flesh is still there. Mine tewaker recipe maker and craft tweaker don’t remove it don’t know why.

**Comment by Corosauce** [comment]
Ah can do, will add a config for the recipe. Also good point about mob drops, I should be able to solve that by making the mob_drops cmod actually replace the mobs loot table instead of just adding to it.
