### ISSUE TITLE
IllegalStateException error

### ISSUE THREAD

**Issue by CalaMariGold** [Corosauce/HostileWorlds_Invasions#22]
https://pastebin.com/mU3dpeMe
`[CoroUtil.difficulty.data.DifficultyDataReader:processFileFromFilesystem:373]: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: "ï»¿"`

This occurs in the console. It (or something) makes all my invasions just become regular invasions (ie, not work). Using commands says the templates don't exist.

mob_spawns.json: https://pastebin.com/AbJp0vzZ
invasion_cmods: https://pastebin.com/0cxsPiE7

**Comment by Corosauce** [comment]
Can I get a full debug log that contains the "Not a JSON Object" error

Otherwise seems to load fine in my setup: 
![2020-03-22_22 28 08](https://user-images.githubusercontent.com/1238621/77274586-a2286900-6c8c-11ea-8aab-95a43476a5b6.png)

**Comment by CalaMariGold** [comment]
[latest.log](https://github.com/Corosauce/HostileWorlds_Invasions/files/4366963/latest.log)

Oops sorry, there it is.

**Comment by Corosauce** [comment]
Hmmm hard to tell exactly why its failing still, might be another file its failing on, not that that explains why the invasions arent loading correctly.

Need to see more debug output, so could you open config/CoroUtil/General.cfg and set both useLoggingDebug and useLoggingLog to true. Then try to run the game again to reproduce the issue which will make a new latest.log then give me that log.

**Comment by cutcat101** [comment]
[latest.log](https://github.com/Corosauce/HostileWorlds_Invasions/files/4379167/latest.log)
mari told me to send this to u

**Comment by Corosauce** [comment]
Issue is caused by changing the files encoding from UTF-8 to UTF-8 BOM, using notepad++ to fix the encoding back to UTF-8 is one way to fix it on your end, or adjust the encoding in whatever editor you use.

Long term plan is ill add in a string.replace("\uFEFF", ""); call to remove this edge case of some editors deciding to change the default encoding of a file.
